systemChat "new game";

JTC_commanderName = name player;
JTC_commanderId = getPlayerUID player;
JTC_playerReputation = JTC_defaultPlayerReputation;
JTC_enemyReputation = JTC_defaultEnemyReputation;
JTC_civilianPopulation = 4000;
JTC_civilianSpawnPercent = 10;
JTC_enemyPopulation = 600;
JTC_freeEnemyPopulation = 0;
JTC_vehiclesKnownToEnemy = [];
JTC_enemyBases = [];
[] call JTC_fnc_initializeCities;
[] call JTC_fnc_initializeBases;
JTC_playerData = [];
{
    [getPlayerUID _x] call JTC_fnc_getPlayerData;
} forEach allPlayers;
publicVariable "JTC_commanderName";
publicVariable "JTC_commanderId";
publicVariable "JTC_playerReputation";
publicVariable "JTC_enemyReputation";
publicVariable "JTC_civilianPopulation";
publicVariable "JTC_civilianSpawnPercent";
publicVariable "JTC_enemyPopulation";
publicVariable "JTC_freeEnemyPopulation";
publicVariable "JTC_vehiclesKnownToEnemy";
publicVariable "JTC_enemyBases";
publicVariable "JTC_cities";
publicVariable "JTC_playerData";
theBase addAction ["Move base", "[false] call JTC_fnc_moveBase;", [], 0, false, true, "", "true", 3];
deployBaseActionId = player addAction ["Deploy base here", "[getPos player] call JTC_fnc_deployBase;", [], 0, false, true, "", "true", 3];
private _marker = createMarker ["hq", getMarkerPos JTC_respawnMarker];
_marker setMarkerType JTC_hqMarkerType;
_marker setMarkerText "Home";
closeDialog 23001;
