["new game"] call JTC_fnc_log;

JTC_commanderName = name player;
JTC_commanderId = getPlayerUID player;
JTC_playerRating = JTC_defaultPlayerRating;
JTC_playerAntirating = JTC_defaultPlayerAntirating;
JTC_enemyRating = JTC_defaultEnemyRating;
JTC_enemyAntirating = JTC_defaultEnemyAntirating;
JTC_freeEnemyPopulation = 0;
JTC_vehiclesKnownToEnemy = [];
JTC_enemyBases = [];
[] call JTC_fnc_initializeCities;
[] call JTC_fnc_initializeBases;
JTC_playerData = [];
{
    [getPlayerUID _x] call JTC_fnc_getPlayerData;
} forEach allPlayers;
publicVariable "JTC_commanderName";
publicVariable "JTC_commanderId";
publicVariable "JTC_playerRating";
publicVariable "JTC_enemyRating";
publicVariable "JTC_playerAntirating";
publicVariable "JTC_enemyAntirating";
publicVariable "JTC_freeEnemyPopulation";
publicVariable "JTC_vehiclesKnownToEnemy";
publicVariable "JTC_enemyBases";
publicVariable "JTC_cities";
publicVariable "JTC_playerData";
theBase addAction ["Move base", "call JTC_fnc_moveBase;", [], 0, false, true, "", "true", 3];
deployBaseActionId = player addAction ["Deploy base here", "[getPosASL player, getDir player] call JTC_fnc_deployBase;", [], 0, false, true, "", "true", 3];
private _marker = createMarker ["hq", getMarkerPos JTC_respawnMarker];
_marker setMarkerType JTC_hqMarkerType;
_marker setMarkerText "Home";
closeDialog 23001;
